<?php
require_once __DIR__.'/../config/db.php';
header('Content-Type: application/json; charset=utf-8');
try{$db=bootstrap_db();}catch(Throwable $e){http_response_code(500);echo json_encode(['ok'=>false,'error'=>'Database unavailable: '.$e->getMessage()]);exit;}
function body(){return json_decode(file_get_contents('php://input'),true)?:$_POST;}
function out($data=[]){echo json_encode(['ok'=>true]+$data);exit;}
function fail($m,$c=400){http_response_code($c);echo json_encode(['ok'=>false,'error'=>$m]);exit;}
function me(){global $db; if(empty($_SESSION['uid']))return null;$s=$db->prepare('SELECT u.*,s.name store_name FROM users u LEFT JOIN stores s ON s.id=u.store_id WHERE u.id=?');$s->execute([$_SESSION['uid']]);return $s->fetch()?:null;}
function require_login(){ $u=me();if(!$u)fail('Login required',401);return $u; }
function admin(){ $u=require_login();if($u['role']!=='admin')fail('Admin permission required',403);return $u; }
function logit($u,$action,$entity='',$id=null,$details=''){global $db;$s=$db->prepare('INSERT INTO audit_logs(user_id,action,entity,entity_id,details,ip_address) VALUES(?,?,?,?,?,?)');$s->execute([$u['id'],$action,$entity,$id,$details,$_SERVER['REMOTE_ADDR']??'']);}
$path=trim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/');$route=preg_replace('#^api/?#','',$path);$method=$_SERVER['REQUEST_METHOD'];$b=body();
if($route==='auth' || $route==='auth.php'){
 if($method==='GET'){ $u=me();$admin_exists=(int)$db->query("SELECT COUNT(*) FROM users WHERE role='admin'")->fetchColumn()>0;out(['logged_in'=>!!$u,'user'=>$u,'admin_exists'=>$admin_exists]); }
 if($method==='POST'){
  $action=$b['action']??'';
  if($action==='register'){if((int)$db->query("SELECT COUNT(*) FROM users WHERE role='admin'")->fetchColumn()>0)fail('Administrator registration is already completed',409);$name=trim($b['full_name']??'');$email=strtolower(trim($b['email']??''));$pass=(string)($b['password']??'');if(strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($pass)<8)fail('Enter valid name, email and password (8+ characters)');$s=$db->prepare("INSERT INTO users(full_name,email,password_hash,role,status) VALUES(?,?,?,?, 'active')");$s->execute([$name,$email,password_hash($pass,PASSWORD_DEFAULT),'admin']);$_SESSION['uid']=$db->lastInsertId();logit(['id'=>$_SESSION['uid']],'admin_registered','user',$_SESSION['uid']);out(['message'=>'Administrator created','user'=>me()]);}
  if($action==='login'){ $email=strtolower(trim($b['email']??''));$pass=(string)($b['password']??'');$s=$db->prepare('SELECT * FROM users WHERE email=?');$s->execute([$email]);$u=$s->fetch();$ok=$u&&$u['status']==='active'&&password_verify($pass,$u['password_hash']);$x=$db->prepare('INSERT INTO login_events(user_id,email,success,ip_address) VALUES(?,?,?,?)');$x->execute([$u['id']??null,$email,$ok?1:0,$_SERVER['REMOTE_ADDR']??'']);if(!$ok)fail('Invalid credentials or inactive account',401);$_SESSION['uid']=$u['id'];logit($u,'login','user',$u['id']);out(['user'=>me()]);}
  if($action==='logout'){if($u=me())logit($u,'logout','user',$u['id']);session_destroy();out(['message'=>'Logged out']);}
 }
}
if($route==='data'){
 $u=require_login();$resource=$b['resource']??$_GET['resource']??'';
 if($resource==='dashboard'){ $where='';$params=[];if($u['role']==='manager'){$where=' WHERE s.store_id=?';$params=[$u['store_id']];}$counts=[];$q=$db->prepare('SELECT COUNT(*) FROM products');$q->execute();$counts['products']=$q->fetchColumn();$q=$db->prepare('SELECT COUNT(*) FROM stores');$q->execute();$counts['stores']=$q->fetchColumn();$q=$db->prepare('SELECT COUNT(*) FROM suppliers');$q->execute();$counts['suppliers']=$q->fetchColumn();$q=$db->prepare('SELECT COALESCE(SUM(st.quantity),0) FROM stock st'.($u['role']==='manager'?' WHERE st.store_id=?':''));$q->execute($u['role']==='manager'?[$u['store_id']]:[]);$counts['units']=$q->fetchColumn();$q=$db->prepare('SELECT COUNT(*) FROM orders'.($u['role']==='manager'?' WHERE store_id=?':''));$q->execute($u['role']==='manager'?[$u['store_id']]:[]);$counts['orders']=$q->fetchColumn();out(['data'=>$counts]);}
 $map=['products'=>'SELECT p.*,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.id DESC','categories'=>'SELECT * FROM categories ORDER BY name','stores'=>'SELECT * FROM stores ORDER BY id','suppliers'=>'SELECT * FROM suppliers ORDER BY name','users'=>'SELECT u.id,u.full_name,u.email,u.role,u.store_id,u.status,u.created_at,s.name store_name FROM users u LEFT JOIN stores s ON s.id=u.store_id ORDER BY u.id DESC','stock'=>'SELECT st.*,p.sku,p.name product_name,p.reorder_level,s.name store_name FROM stock st JOIN products p ON p.id=st.product_id JOIN stores s ON s.id=st.store_id '.($u['role']==='manager'?'WHERE st.store_id='.((int)$u['store_id']):'').' ORDER BY st.quantity ASC','stock_history'=>'SELECT sm.*,p.name product_name,s.name store_name,u.full_name user_name FROM stock_movements sm JOIN products p ON p.id=sm.product_id JOIN stores s ON s.id=sm.store_id LEFT JOIN users u ON u.id=sm.user_id '.($u['role']==='manager'?'WHERE sm.store_id='.((int)$u['store_id']):'').' ORDER BY sm.id DESC','purchases'=>'SELECT pu.*,s.name store_name,sp.name supplier_name,u.full_name requester FROM purchases pu JOIN stores s ON s.id=pu.store_id LEFT JOIN suppliers sp ON sp.id=pu.supplier_id LEFT JOIN users u ON u.id=pu.requested_by '.($u['role']==='manager'?'WHERE pu.store_id='.((int)$u['store_id']):'').' ORDER BY pu.id DESC','orders'=>'SELECT * FROM orders '.($u['role']==='manager'?'WHERE store_id='.((int)$u['store_id']):'').' ORDER BY id DESC','returns'=>'SELECT r.*,o.customer_name customer_order_name FROM returns r LEFT JOIN orders o ON o.id=r.order_id '.($u['role']==='manager'?'WHERE r.store_id='.((int)$u['store_id']):'').' ORDER BY r.id DESC','audit'=>'SELECT a.*,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id '.($u['role']==='manager'?'WHERE a.user_id='.((int)$u['id']):'').' ORDER BY a.id DESC','login_events'=>'SELECT * FROM login_events ORDER BY id DESC LIMIT 200','notifications'=>'SELECT * FROM notifications WHERE user_id IS NULL OR user_id='.((int)$u['id']).' ORDER BY id DESC','settings'=>'SELECT * FROM settings WHERE id=1'];
 if(!isset($map[$resource]))fail('Unknown resource');$rows=$db->query($map[$resource])->fetchAll();out(['data'=>$rows]);
}
if($route==='action'){
 $u=require_login();$a=$b['action']??'';
 $adminOnly=['delete_product','delete_category','create_category','update_category','delete_supplier','create_supplier','update_supplier','create_store','update_store','delete_store','create_manager','update_user','delete_user','assign_manager','settings','approve_return','reject_return','refund_return','approve_purchase','reject_purchase','restore_backup'];
 if(in_array($a,$adminOnly,true)&&$u['role']!=='admin')fail('This action is restricted to administrators',403);
 if($a==='product_save'){ $id=(int)($b['id']??0);$vals=[trim($b['sku']??''),trim($b['name']??''),(int)($b['category_id']??0),$b['description']??'',(float)($b['unit_price']??0),(float)($b['cost_price']??0),(int)($b['reorder_level']??10),$b['status']??'active'];if(!$vals[0]||!$vals[1])fail('SKU and product name are required');if($id){$s=$db->prepare('UPDATE products SET sku=?,name=?,category_id=?,description=?,unit_price=?,cost_price=?,reorder_level=?,status=? WHERE id=?');$s->execute([...$vals,$id]);logit($u,'product_updated','product',$id);}else{$s=$db->prepare('INSERT INTO products(sku,name,category_id,description,unit_price,cost_price,reorder_level,status) VALUES(?,?,?,?,?,?,?,?)');$s->execute($vals);$id=$db->lastInsertId();logit($u,'product_created','product',$id);}out(['message'=>'Product saved']);}
 if($a==='delete_product'){$id=(int)$b['id'];$db->prepare('DELETE FROM products WHERE id=?')->execute([$id]);logit($u,'product_deleted','product',$id);out();}
 if($a==='category_save'){ $id=(int)($b['id']??0);if($id){$s=$db->prepare('UPDATE categories SET name=?,description=?,status=? WHERE id=?');$s->execute([$b['name'],$b['description']??'',$b['status']??'active',$id]);}else{$s=$db->prepare('INSERT INTO categories(name,description,status) VALUES(?,?,?)');$s->execute([$b['name'],$b['description']??'','active']);}out();}
 if($a==='delete_category'){$db->prepare('DELETE FROM categories WHERE id=?')->execute([(int)$b['id']]);out();}
 if($a==='supplier_save'){ $id=(int)($b['id']??0);$v=[$b['name'],$b['email']??'',$b['phone']??'',$b['address']??'',$b['status']??'active'];if($id){$s=$db->prepare('UPDATE suppliers SET name=?,email=?,phone=?,address=?,status=? WHERE id=?');$s->execute([...$v,$id]);}else{$s=$db->prepare('INSERT INTO suppliers(name,email,phone,address,status) VALUES(?,?,?,?,?)');$s->execute($v);}out();}
 if($a==='delete_supplier'){$db->prepare('DELETE FROM suppliers WHERE id=?')->execute([(int)$b['id']]);out();}
 if($a==='store_save'){ $id=(int)($b['id']??0);$v=[$b['name'],$b['code'],$b['address']??'',$b['status']??'active'];if($id){$s=$db->prepare('UPDATE stores SET name=?,code=?,address=?,status=? WHERE id=?');$s->execute([...$v,$id]);}else{$s=$db->prepare('INSERT INTO stores(name,code,address,status) VALUES(?,?,?,?)');$s->execute($v);}out();}
 if($a==='delete_store'){$db->prepare('DELETE FROM stores WHERE id=?')->execute([(int)$b['id']]);out();}
 if($a==='user_save'){ $id=(int)($b['id']??0);$role=$b['role']??'manager';if($id){$s=$db->prepare('UPDATE users SET full_name=?,email=?,role=?,store_id=?,status=? WHERE id=?');$s->execute([$b['full_name'],$b['email'],$role,$b['store_id']?:null,$b['status']??'active',$id]);}else{$pass=$b['password']??'';if(strlen($pass)<8)fail('Password must be 8+ characters');$s=$db->prepare('INSERT INTO users(full_name,email,password_hash,role,store_id,status) VALUES(?,?,?,?,?,?)');$s->execute([$b['full_name'],$b['email'],password_hash($pass,PASSWORD_DEFAULT),$role,$b['store_id']?:null,'active']);$id=$db->lastInsertId();}logit($u,'user_saved','user',$id);out();}
 if($a==='delete_user'){$id=(int)$b['id'];if($id==$u['id'])fail('You cannot delete your own account');$db->prepare('DELETE FROM users WHERE id=?')->execute([$id]);out();}
 if($a==='assign_manager'){$db->prepare("UPDATE users SET store_id=? WHERE id=? AND role='manager'")->execute([(int)$b['store_id'],(int)$b['user_id']]);out();}
 if($a==='stock_adjust'){ $sid=$u['role']==='manager'?(int)$u['store_id']:(int)$b['store_id'];$pid=(int)$b['product_id'];$qty=(int)$b['quantity'];$type=$b['type']==='out'?'out':($b['type']==='in'?'in':'adjustment');$s=$db->prepare('SELECT quantity FROM stock WHERE store_id=? AND product_id=?');$s->execute([$sid,$pid]);$old=(int)$s->fetchColumn();$new=$type==='in'?$old+$qty:($type==='out'?$old-$qty:$qty);if($new<0)fail('Insufficient stock');$db->prepare('INSERT INTO stock(store_id,product_id,quantity,reserved) VALUES(?,?,?,0) ON DUPLICATE KEY UPDATE quantity=VALUES(quantity)')->execute([$sid,$pid,$new]);$db->prepare('INSERT INTO stock_movements(store_id,product_id,user_id,type,quantity,reason) VALUES(?,?,?,?,?,?)')->execute([$sid,$pid,$u['id'],$type,$qty,$b['reason']??'Manual stock adjustment']);logit($u,'stock_adjusted','stock',$pid,'Store '.$sid);out();}
 if($a==='order_status'){$id=(int)$b['id'];$s=$db->prepare('UPDATE orders SET status=? WHERE id=?');$s->execute([$b['status'],$id]);out();}
 if($a==='return_status'){$id=(int)$b['id'];$status=$b['status'];$s=$db->prepare('UPDATE returns SET status=?,refund_amount=? WHERE id=?');$s->execute([$status,(float)($b['refund_amount']??0),$id]);out();}
 if($a==='purchase_status'){$id=(int)$b['id'];$db->prepare('UPDATE purchases SET status=? WHERE id=?')->execute([$b['status'],$id]);out();}
 if($a==='profile'){ $name=trim($b['full_name']??'');$email=strtolower(trim($b['email']??''));if(strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL))fail('Enter a valid name and email');$s=$db->prepare('UPDATE users SET full_name=?,email=? WHERE id=?');$s->execute([$name,$email,$u['id']]);if(!empty($b['password'])){if(strlen((string)$b['password'])<8)fail('Password must be at least 8 characters');$db->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($b['password'],PASSWORD_DEFAULT),$u['id']]);}$fresh=me();logit($fresh,'profile_updated','user',$fresh['id']);out(['message'=>'Profile updated','user'=>$fresh]);}
 if($a==='settings'){ $db->prepare('UPDATE settings SET site_name=?,currency=?,low_stock_alert=? WHERE id=1')->execute([$b['site_name'],$b['currency'],$b['low_stock_alert']?1:0]);out();}
 if($a==='backup'){ $path=__DIR__.'/../database/backups';if(!is_dir($path))mkdir($path,0777,true);$file=$path.'/backup_'.date('Ymd_His').'.sql';$tables=$db->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);$fh=fopen($file,'w');foreach($tables as $t){fwrite($fh,"-- $t\n");$rows=$db->query("SELECT * FROM `$t`")->fetchAll();if($rows){$cols=array_keys($rows[0]);foreach($rows as $r){$vals=[];foreach($cols as $c)$vals[]=$db->quote($r[$c]);fwrite($fh,'INSERT INTO `'.$t.'` (`'.implode('`,`',$cols).'`) VALUES ('.implode(',',$vals).');'.PHP_EOL);}}}fclose($fh);out(['message'=>'Backup created: '.basename($file)]);}
 fail('Unknown action');
}
fail('Route not found',404);
